apiVersion: v1
kind: ConfigMap
metadata:
  name: homebrew-config
  namespace: homebrew
data:
  BETTER_AUTH_URL: "https://homebrew.example.com"
  OTEL_SERVICE_NAME: "homebrewapp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"
