apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebrew
  namespace: homebrew
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - homebrew.example.com
      secretName: homebrew-tls
  rules:
    - host: homebrew.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homebrew
                port:
                  name: http
